### PR TITLE
hitesh mewada

### PR DESCRIPTION
**Pull request by hiteshmewada**

### CODE REVIEW

**Comment by ameybh** [comment]
@hiteshmewada Please replace the base 64 image data with an image url. You can upload your choice of image to any image hosting platform and use that url, for example [Imgur](https://imgur.com/upload).

**Review by ameybh — CHANGES_REQUESTED** [review]
Replace base 64 with image url.

**Comment by hiteshmewada** [comment]
ok, sure

**Review by ameybh — APPROVED** [review]
Looks good.

**Pull request merged**
